namespace Vicuñas.Dtos
{
    public enum Idiomaenum
    {
        Ninguno = 0,
        Afroboliviano = 1,
        Araona = 2,
        Aymara = 3,
        Ayoreo = 4,
        Baures = 5,
        Canichana = 6,
        Cabineño = 7,
        Cayubaba = 8,
        Chácobo = 9,
        Chimán = 10,
        Chiquitano= 11,
        Eseeja = 12,
        Guarani = 13,
        Guarasugwe = 14,
        Gwarayu = 15,
        Ilonama = 16,
        Leco = 17,
        Kallawaya = 18,
        Machineri = 19,
        Maropa = 20,
        Mojos_Ignaciano = 21,
        Mojeño_Trinitario = 22,
        More = 23,
        Mosetan = 24,
        Movima = 25,
        Pacawara = 26,
        Pukina = 27,
        Quechua = 28,
        Sirfono = 29,
        Tacana = 30,
        Tapiete = 31,
        Toromona = 32,
        Uru_Chipaya = 33,
        Weenhayek = 34,
        Yaminahua = 35,
        Yuki = 36,
        Yuracare = 37,
    }
}
