// <auto-generated />
using System;
using Micontexto.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Vicuñas.Migrations
{
    [DbContext(typeof(ContextoV))]
    [Migration("20251012145636_Migra123")]
    partial class Migra123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstudiantePadre", b =>
                {
                    b.Property<int>("EstudiantesId")
                        .HasColumnType("int");

                    b.Property<int>("TutoresId")
                        .HasColumnType("int");

                    b.HasKey("EstudiantesId", "TutoresId");

                    b.HasIndex("TutoresId");

                    b.ToTable("EstudiantePadre");
                });

            modelBuilder.Entity("Vicuñas.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_M")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Apellido_P")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CI")
                        .HasColumnType("int");

                    b.Property<int>("Certificado_Folio")
                        .HasColumnType("int");

                    b.Property<int>("Certificado_Libro")
                        .HasColumnType("int");

                    b.Property<int>("Certificado_Oficialia")
                        .HasColumnType("int");

                    b.Property<int>("Certificado_Partida")
                        .HasColumnType("int");

                    b.Property<string>("Ci_Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ci_Expedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discapacidad")
                        .HasColumnType("bit");

                    b.Property<bool>("Extranjero")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Nac")
                        .HasColumnType("date");

                    b.Property<bool>("Inscrito")
                        .HasColumnType("bit");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nro_Celular")
                        .HasColumnType("int");

                    b.Property<int>("Nro_Discapacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nro_Documento_Extranjero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nro_Rude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nro_Telefono")
                        .HasColumnType("int");

                    b.Property<int>("Nro_Vivienda")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParaleloId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Programa_Apoyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tipo_Auditiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Discapacidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Documento_Extranjero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Fisica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Intelectual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Mental")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Visual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParaleloId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Vicuñas.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("Vicuñas.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Agua")
                        .HasColumnType("bit");

                    b.Property<bool>("Alcantarillado")
                        .HasColumnType("bit");

                    b.Property<bool>("Banio")
                        .HasColumnType("bit");

                    b.Property<bool>("Basurero")
                        .HasColumnType("bit");

                    b.Property<bool>("Centro_Salud")
                        .HasColumnType("bit");

                    b.Property<bool>("Electricidad")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoAbandono")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado_Laburo")
                        .HasColumnType("bit");

                    b.Property<int?>("EstudianteCi")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Frecuencia_Internet")
                        .HasColumnType("int");

                    b.Property<int>("Frecuencia_Laburo")
                        .HasColumnType("int");

                    b.Property<int>("Frecuencia_Salud")
                        .HasColumnType("int");

                    b.Property<string>("Idioma_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idioma_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idiomas")
                        .HasColumnType("int");

                    b.Property<int>("Internet")
                        .HasColumnType("int");

                    b.Property<string>("Laburo_Otro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Medio_Transporte")
                        .HasColumnType("int");

                    b.Property<string>("Medio_Transporte_Otro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Motivo")
                        .HasColumnType("int");

                    b.Property<string>("MovilidadOtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otro_Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int?>("ParaleloId")
                        .HasColumnType("int");

                    b.Property<bool>("Seguro_Salud")
                        .HasColumnType("bit");

                    b.Property<int>("Tiempo_Transporte")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Laburo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Medicacion")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Pago")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Vivienda")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<int?>("TutorCi")
                        .HasColumnType("int");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCi")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ParaleloId")
                        .IsUnique()
                        .HasFilter("[ParaleloId] IS NOT NULL");

                    b.HasIndex("TutorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("Vicuñas.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCi")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Vicuñas.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteCi")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("Trimestre")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCi")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("Vicuñas.Models.Padre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_M")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Apellido_P")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CI")
                        .HasColumnType("int");

                    b.Property<string>("Ci_Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ci_Expedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Educacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Nac")
                        .HasColumnType("date");

                    b.Property<string>("Idioma1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Laburo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo_Tutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Padres");
                });

            modelBuilder.Entity("Vicuñas.Models.Paralelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<int?>("GradoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Paralelos");
                });

            modelBuilder.Entity("Vicuñas.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioCi")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Vicuñas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_M")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Apellido_P")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CI")
                        .HasColumnType("int");

                    b.Property<string>("Ci_Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<float>("Sueldo")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstudiantePadre", b =>
                {
                    b.HasOne("Vicuñas.Models.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vicuñas.Models.Padre", null)
                        .WithMany()
                        .HasForeignKey("TutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vicuñas.Models.Estudiante", b =>
                {
                    b.HasOne("Vicuñas.Models.Paralelo", "Paralelo")
                        .WithMany("Estudiantes")
                        .HasForeignKey("ParaleloId");

                    b.Navigation("Paralelo");
                });

            modelBuilder.Entity("Vicuñas.Models.Inscripcion", b =>
                {
                    b.HasOne("Vicuñas.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("Vicuñas.Models.Paralelo", "Paralelo")
                        .WithOne("Inscripcion")
                        .HasForeignKey("Vicuñas.Models.Inscripcion", "ParaleloId");

                    b.HasOne("Vicuñas.Models.Padre", "Tutor")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TutorId");

                    b.HasOne("Vicuñas.Models.Usuario", "Usuario")
                        .WithMany("Inscripciones")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Estudiante");

                    b.Navigation("Paralelo");

                    b.Navigation("Tutor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vicuñas.Models.Materia", b =>
                {
                    b.HasOne("Vicuñas.Models.Usuario", "Usuario")
                        .WithMany("Materias")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vicuñas.Models.Nota", b =>
                {
                    b.HasOne("Vicuñas.Models.Estudiante", "Estudiante")
                        .WithMany("Notas")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("Vicuñas.Models.Materia", "Materia")
                        .WithMany("Notas")
                        .HasForeignKey("MateriaId");

                    b.HasOne("Vicuñas.Models.Usuario", "Usuario")
                        .WithMany("Notas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vicuñas.Models.Paralelo", b =>
                {
                    b.HasOne("Vicuñas.Models.Grado", "Grado")
                        .WithMany("Paralelos")
                        .HasForeignKey("GradoId");

                    b.HasOne("Vicuñas.Models.Usuario", "Usuario")
                        .WithMany("Paralelos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Grado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vicuñas.Models.Reporte", b =>
                {
                    b.HasOne("Vicuñas.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vicuñas.Models.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Vicuñas.Models.Grado", b =>
                {
                    b.Navigation("Paralelos");
                });

            modelBuilder.Entity("Vicuñas.Models.Materia", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Vicuñas.Models.Padre", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Vicuñas.Models.Paralelo", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("Vicuñas.Models.Usuario", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Materias");

                    b.Navigation("Notas");

                    b.Navigation("Paralelos");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
